defaults:
  - defaults.yaml
  - _self_

dataset: LENDB
batch_size: 1024
n_epoch: 80
z_dim: 96
n_domains: 10
data_dir: /Data/LENDB
lr: 5e-3
lr_decay: 0.1
weight_decay: 5e-4
metric_list: ['mae', 'mse']
use_batch_norm: True
w_pred: 1.
w_oa: .1
w_dtg: .1